name: 'olist_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_analytics:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table
